### ISSUE TITLE
complete translation of UI

### ISSUE THREAD

**Issue by arve0** [arve0/codeclub_lesson_builder#201]
The UI should handle:
- [ ] `index.md` in different languages
- [ ] show only courses / lessons for selected language
- [ ] save / restore state with `localStorage`
- [ ] propose lesson in different language if `languages` is set in YAML
  
  ``` yaml
  ---
  title: Straffespark
  languages:
    nn-NO: straffespark.nn.md
    en-GB: penalty.md
  ---
  ```

Ref: https://github.com/kodeklubben/oppgaver/issues/170
